name: Control Dockerfiles
on:
  push:
    paths:
      - 'Dockerfile*'
      - '.github/workflows/build-dockerfile.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Control that Dockerfile builds
        run: |
          archs='aarch64 armv7hf'
          testtag=buildcheck
          for arch in $archs
          do
            printf "\n\n### Build for $arch\n"
            docker build -t $testtag:$arch --build-arg ARCH=$arch .
          done

          for arch in $archs
          do
            printf "\n\n### Clean Dockerfile.$arch\n"
            docker image rm -f $testtag:$arch
          done

          printf "\n\n### All Dockerfiles build"
